server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order-service?createDatabaseIfNotExist=true
    username: root
    password: FAmi12@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect


product-service:
  url: http://localhost:8081

inventory-service:
  url: http://localhost:8082